//! PeridotID smart account program.
//!
//! A non-custodial Solana smart account (PDA) that owns the user's assets. The asset
//! controlling authority for V1 is an **Ed25519 device key** that signs the transaction
//! directly (ADR 005 Option A — invoked via the ADR 005 fallback: Pinocchio has no
//! instruction introspection for the secp256r1 precompile pattern, see the task file).
//! The `authority_type` discriminant in state keeps the secp256r1 passkey path open.
//!
//! The program verifies authorization by requiring the registered authority account to be
//! a transaction signer (`is_signer`) whose address equals `state.authority`. The Solana
//! runtime verifies that signer's Ed25519 signature over the entire transaction message —
//! which includes this instruction's nonce/amount/destination — binding the authorization
//! to the exact action (PRD_v4 §24/§25).

#![no_std]
#![allow(unexpected_cfgs)]

extern crate alloc;

pub mod auth;
pub mod errors;
pub mod instructions;
pub mod secp256r1;
pub mod sha256;
pub mod state;

use pinocchio::{error::ProgramError, program_entrypoint, AccountView, Address, ProgramResult};

use instructions::{Instruction, InstructionData};

pinocchio::address::declare_id!("CiwLJ1hMNjSRdZj2yMVt9BseRTjVd4pjz7Mxr9yXf6NT");

program_entrypoint!(process_instruction);
pinocchio::default_allocator!();
pinocchio::nostd_panic_handler!();

/// Process a Peridot smart-account instruction.
///
/// # Safety
/// The entrypoint is generated by the `entrypoint!` macro; the unsafe deserialization is
/// contained there.
pub fn process_instruction(
    program_id: &Address,
    accounts: &[AccountView],
    instruction_data: &[u8],
) -> ProgramResult {
    if program_id != &ID {
        return Err(ProgramError::IncorrectProgramId);
    }

    let (discriminator, data) = instruction_data
        .split_first()
        .ok_or(ProgramError::InvalidInstructionData)?;
    let instruction_data = InstructionData::new(data)?;

    match Instruction::try_from(*discriminator)? {
            Instruction::Initialize => instructions::initialize::process(program_id, accounts, &instruction_data),
            Instruction::WithdrawSol => instructions::withdraw_sol::process(program_id, accounts, &instruction_data),
            Instruction::WithdrawToken => instructions::withdraw_token::process(program_id, accounts, &instruction_data),
            Instruction::UpdateAuthority => instructions::update_authority::process(program_id, accounts, &instruction_data),
            Instruction::Close => instructions::close::process(program_id, accounts, &instruction_data),
            Instruction::Activate => instructions::activate::process(program_id, accounts, &instruction_data),
        }
}