//! PeridotID smart account program.
//!
//! A non-custodial Solana smart account (PDA) that owns the user's assets. The asset
//! controlling authority is a secp256r1 (P-256) WebAuthn passkey (ADR 005 Option B):
//! the SDK places a Secp256r1 precompile instruction immediately after this
//! program's instruction and the program verifies it via the Instructions sysvar
//! (`auth.rs::verify_secp256r1_v2`), enforcing stored-authority match, RP-ID hash,
//! user-verification flag, exact `authenticatorData ‖ sha256(clientDataJSON)`
//! message binding, and equality of the WebAuthn challenge with the V2
//! domain-separated authorization payload recomputed from instruction args.
//!
//! V2 authorization schema (`contracts/V2_AUTHORIZATION.md`, canonical): every
//! payload starts with `DOMAIN_V2 ‖ op-tag ‖ account_id`, the user authorizes an
//! absolute `max_fee` (never an exact fee), and reimbursement splits base →
//! relayer (fee payer) and markup → canonical treasury per the signed
//! fee-policy version. State is versioned (v1 80B legacy-readable, v2 112B with
//! RP-ID hash); rotation never moves the PDA.

#![no_std]
#![allow(unexpected_cfgs)]

extern crate alloc;

pub mod auth;
pub mod errors;
pub mod fee;
pub mod instructions;
pub mod secp256r1;
pub mod sha256;
pub mod state;

/// Backend allowlist + canonical treasury, baked at build time by `build.rs`
/// from `PID_BACKEND` / `PID_TREASURY`. Creation paths require the payer/relayer
/// to equal `BACKEND` (PID-ownership proof); fee markup goes to `TREASURY`.
pub mod config {
    include!(concat!(env!("OUT_DIR"), "/config.rs"));
}

use pinocchio::{error::ProgramError, program_entrypoint, AccountView, Address, ProgramResult};

use instructions::{Instruction, InstructionData};

pinocchio::address::declare_id!("CiwLJ1hMNjSRdZj2yMVt9BseRTjVd4pjz7Mxr9yXf6NT");

program_entrypoint!(process_instruction);
pinocchio::default_allocator!();
pinocchio::nostd_panic_handler!();

/// Process a Peridot smart-account instruction.
///
/// # Safety
/// The entrypoint is generated by the `entrypoint!` macro; the unsafe deserialization is
/// contained there.
pub fn process_instruction(
    program_id: &Address,
    accounts: &[AccountView],
    instruction_data: &[u8],
) -> ProgramResult {
    if program_id != &ID {
        return Err(ProgramError::IncorrectProgramId);
    }

    let (discriminator, data) = instruction_data
        .split_first()
        .ok_or(ProgramError::InvalidInstructionData)?;
    let instruction_data = InstructionData::new(data)?;

    match Instruction::try_from(*discriminator)? {
            Instruction::Initialize => instructions::initialize::process(program_id, accounts, &instruction_data),
            Instruction::WithdrawSol => instructions::withdraw_sol::process(program_id, accounts, &instruction_data),
            Instruction::WithdrawToken => instructions::withdraw_token::process(program_id, accounts, &instruction_data),
            Instruction::UpdateAuthority => instructions::update_authority::process(program_id, accounts, &instruction_data),
            Instruction::Close => instructions::close::process(program_id, accounts, &instruction_data),
            Instruction::Activate => instructions::activate::process(program_id, accounts, &instruction_data),
            Instruction::Execute => instructions::execute::process(program_id, accounts, &instruction_data),
        }
}