// PeridotID core primitives — reusable identity/crypto/hash building blocks.
//
// Layering (web3.js layering rule): pid-core owns dependency-free primitives plus the key
// types both layers share. pid-solana (chain adapter/instructions) and pid-sdk-js
// (direct API client) build on top. The public login UX (redirects, hosted login,
// prod defaults) lives in pid-react and must never leak down here: no navigation,
// no hosts, no app flow.

export {
  buildActivatePayload,
  buildActivatePayloadV2,
  buildActivatePayloadV3,
  buildAuthorizationPayload,
  buildAuthorizationPayloadV2,
  buildAuthorizationPayloadV3,
  buildClosePayloadV2,
  buildClosePayloadV3,
  buildCloseSessionPayload,
  buildExecutePayloadV3,
  buildRegisterSessionPayload,
  buildRevokeSessionPayload,
  buildSessionPayload,
  executeCallHash,
  EXECUTE_FLAG,
  MAX_EXECUTE_DATA,
  MAX_EXECUTE_METAS,
  serializeExecuteCall,
  buildInitializePayload,
  buildInitializePayloadV2,
  buildInitializePayloadV3,
  buildUpdateAuthorityPayloadV2,
  buildUpdateAuthorityPayloadV3,
  buildWebAuthnMessage,
  buildWithdrawPayload,
  buildWithdrawPayloadV2,
  buildWithdrawPayloadV3,
  buildWithdrawTokenPayload,
  buildWithdrawTokenPayloadV2,
  buildWithdrawTokenPayloadV3,
  deriveSmartAccountAddress,
  deriveSessionAddress,
  deriveProgramDataAddress,
  DOMAIN,
  DOMAIN_SESSION,
  DOMAIN_V2,
  DOMAIN_V3,
  INSTRUCTIONS_SYSVAR,
  BPF_LOADER_UPGRADEABLE,
  IX,
  IX_SESSION,
  MAX_PROTECTED,
  MAX_SESSION_DATA,
  MAX_SESSION_METAS,
  OP,
  OP_SESSION,
  SESSION_FLAG,
  SESSION_INACTIVITY_SECS,
  SESSION_MAX_TTL_SECS,
  SESSION_STATE_LEN,
  serializeSessionMetas,
  PID_PROGRAM_ID,
  SECP256R1_PRECOMPILE,
  sha256,
} from "./hash";
export {
  pidToSeed32,
  sha256Sync,
  asciiOf,
  b64url,
  b64urlToBytes,
  concat,
  derToRawEcdsa,
  fromAscii,
  fromHex,
  i64le,
  normalizeLowS,
  SECP256R1_ORDER,
  toHex,
  u16le,
  u64le,
} from "./bytes";
export type { Bytes } from "./bytes";
export type { ExecuteMeta, SessionMeta } from "./hash";
export {
  assertCeremonyOrigin,
  authenticatePasskey,
  BrowserPasskeySigner,
  PasskeyHostedRequiredError,
  registerPasskey,
} from "./webauthn";
export type { PasskeyAssertion, PasskeySigner } from "./webauthn";
export {
  pidToSalt32,
  addressToBytes,
  buildEvmAuthorizationPayload,
  buildEvmAuthorizationPayloadV2,
  buildEvmAuthorizationPayloadV3,
  compressedToX,
  deriveEvmSmartAccountAddress,
  DOMAIN_EVM,
  DOMAIN_EVM_V2,
  DOMAIN_EVM_V3,
  EVM_CHAINS,
  getCreate2Address,
  keccak256,
  minimalProxyInitCode,
  OP_EVM,
  splitRawXy,
  toChecksumAddress,
} from "./evm";
export type { EvmChain } from "./evm";
export {
  FeePayerManager,
  InMemorySecretStore,
  LocalStorageSecretStore,
  type SecretStore,
} from "./custody";
export { LocalHistoryStore, type HistoryStore } from "./cache";
export { Keypair, PublicKey } from "@solana/web3.js";
export type { Keypair as SolanaKeypair } from "@solana/web3.js";
